version = 0.1

[1]
[1.global]
[1.global.parameters]
stack_name = "unicorn-properties-dev-contracts"
s3_prefix = "unicorn-properties-dev-contracts"
s3_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-jokwgdwov3hr"
region = "us-east-1"

[1.deploy]
[1.deploy.parameters]
template = "packaged-testing.yaml"
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Stage=dev"


# ############################################## #

[2]
[2.global]
[2.global.parameters]
stack_name = "unicorn-properties-prod-contracts"
s3_prefix = "unicorn-properties-prod-contracts"
s3_bucket = ""
region = "us-east-1"

[1.deploy]
[1.deploy.parameters]
template = "packaged-testing.yaml"
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Stage=prod"


# ############################################## #

[pipeline]
[pipeline.deploy]
[pipeline.deploy.parameters]
stack_name = "unicorn-properties-contracts-pipeline"
s3_prefix = "unicorn-properties-contracts-pipeline"
resolve_s3 = true
fail_on_empty_changeset = false
template = "codepipeline.yaml"
capabilities = "CAPABILITY_IAM"
