version: 0.1

default:
  global:
    parameters:
      stack_name: unicorn-properties-local-properties
      s3_prefix: unicorn-properties-local-properties
      s3_bucket: 8586-terraform-state
      # resolve_s3: true
      resolve_image_repositories: true
  build:
    parameters:
      cached: true
      parallel: true
  deploy:
    parameters:
      disable_rollback: false
      confirm_changeset: false
      fail_on_empty_changeset: false
      capabilities:
        - CAPABILITY_IAM
        - CAPABILITY_AUTO_EXPAND
      parameter_overrides:
        - "Stage=local"
  validate:
    parameters:
      lint: true
  sync:
    parameters:
      watch: true
  local_start_api:
    parameters:
      warm_containers: EAGER
  local_start_lambda:
    parameters:
      warm_containers: EAGER
